### ISSUE TITLE
在最近的DBM更新中 M王座女巫议会出现了一个问题

### ISSUE THREAD

**Issue by Caponia** [Mini-Dragon/DBM-VoicePack-Yike#1]
宇宙之母在场并且需要打断的时候会提示 一断二断三断快打断一断二断三断

我记得之前的版本都是一断二断三断  没有快打断

请问有办法解决吗？

**Comment by Mini-Dragon** [comment]
Hello, 语音包只负责播放语音(play something)，不负责怎么播放(what to play and how). 调用语音是dbm本体完成的。
However 这个问题也许是你没有在对应的boss模组中选择自己的打断职责。
