### ISSUE TITLE
是不是该更新了....

### ISSUE THREAD

**Issue by Sanluli36li** [Mini-Dragon/DBM-VoicePack-Yike#3]
前阵子刚开前夕的时候说up一下版本

不会我开个玩笑成真了吧...

**Comment by Mini-Dragon** [comment]
你看我不是把toc更新了

**Comment by Sanluli36li** [comment]
好吧也许应该传一下twitch?

**Comment by liugongkai111** [comment]
大佬, 是否考虑更新一下Twitch上的语音包?

**Comment by Mini-Dragon** [comment]
各位大佬，由于一可和小弟并没有做什么实质上的更新，所以等开副本前统一更新一次。大家都上github了自己手动改一下toc文件应该不是什么大问题吧（望天）。强迫症就没有办法了。:D

**Comment by Mini-Dragon** [comment]
update and upload
