### ISSUE TITLE
辛苦大佬，能不能上传一下Twitch？我帮你传也行……

### ISSUE THREAD

**Issue by ayd13swb** [Mini-Dragon/DBM-VoicePack-Yike#4]
早就更新了TOC，但是Twitch一直显示的是已修改，强迫症好难受………………

对了，另外劳驾问一下，VEM语音有相比一可的更新语音文件么？还是大家其实都只是在更新Toc版本……

**Comment by Mini-Dragon** [comment]
Hello! 由于具体的语音文件还在编排录音，我打算在开副本之前统一更新一次。

**Comment by ayd13swb** [comment]
得嘞，那辛苦鸽鸽，不对，哥哥。

**Comment by Mini-Dragon** [comment]
update and upload

**Comment by ayd13swb** [comment]
更新的是这个github的吧，不是twitch？我就确定一下，不是催大佬。：）

**Comment by Mini-Dragon** [comment]
每一个包，twitch工作人员都要人工审核啊。正在审核。
