### ISSUE TITLE
curse版本问题

### ISSUE THREAD

**Issue by JeremyLuan** [Mini-Dragon/DBM-VoicePack-Yike#7]
作者大佬，请问9.0.1版本的语音包在curse上是不是发错版本了，使用curse客户端检查更新，retail版最新版仍然是8.2版本，classic版却变成了9.0.1，需要手动把classic版复制到retail文件夹里面

**Comment by Mini-Dragon** [comment]
我新加了个语音 应该修正了 祝使用愉快
